version: "3.9"
services:
  room-web-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: room-web-server
    container_name: room-web-server
    ports:
      - "8000:8000"
    environment:
      PASSWORD_SALT: ${PASSWORD_SALT}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: local-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GIN_MODE: debug
    depends_on:
      local-db:
        condition: service_started
  local-db:
    image: postgres:latest
    restart: always
    container_name: local-room-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local