version: "3.9"
services:
  room-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: room-webserver:latest
    container_name: room-webserver
    ports:
      - "8000:8000"
    environment:
      PASSWORD_SALT: ${PASSWORD_SALT}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: local-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      GIN_MODE: debug
    working_dir: /usr/src/project
    entrypoint: ["gowatch"]
    volumes:
      - type: bind
        source: .
        target: /usr/src/project
    depends_on:
      local-db:
        condition: service_started
  local-db:
    image: postgres:latest
    restart: always
    container_name: local-room-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - local-room-db:/var/lib/postgresql/data
volumes:
  local-room-db:
    driver: local
